onlycerts:
  namespace:
vault:
  address: https://vault.int.netigate-sre.com
services:
  - name:
    description:
    certificates:
    pullSecrets:
    roleBinding:
      enable:
      activeDirectory:
        group:
          objectID: