apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    team: {{ .Values.team }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        team: {{ .Values.team }}
      annotations:
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/log-format: json
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "{{ .Values.name }}"
        vault.hashicorp.com/agent-inject-secret-config: "{{ .Values.vault.team }}/data/{{ .Values.name }}/config"
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if or .Values.grpc.enabled .Values.grpcExt.enabled .Values.postgres.enabled .Values.vault.env .Values.kafka.enable }}
          env:
            {{- if .Values.vault.env }}
            {{- range .Values.vault.env }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.name }}-secret
                  key: {{ .key }}
            {{- end }}
            {{- end }}
            {{- if or .Values.grpc.enabled .Values.grpcExt.enabled }}
            - name: Kestrel__Endpoints__HttpsInlineCertAndKeyFile__Url
              value: https://+:443
            {{- end }}
            {{- if .Values.postgres.enabled }}
            - name: ConnectionStrings__PostgresContext
              valueFrom:
                secretKeyRef:
                  name: postgres-{{ .Values.postgres.databaseServer }}-{{ .Values.postgres.databaseName }}
                  key: postgresConnectionString
            {{- end }}
            {{- if .Values.kafka.enabled }}
            - name: EventBus__BootStrapServers
              valueFrom:
                secretKeyRef:
                  name: kafka-{{ .Values.kafka.cluster }}-{{ .Values.kafka.app }}
                  key: service_uri
            - name: EventBus__SchemaRegistry__Username
              valueFrom:
                secretKeyRef:
                  name: kafka-{{ .Values.kafka.cluster }}-{{ .Values.kafka.app }}
                  key: username
            - name: EventBus__SchemaRegistry__Url
              valueFrom:
                secretKeyRef:
                  name: kafka-{{ .Values.kafka.cluster }}-{{ .Values.kafka.app }}
                  key: schema_registry_uri
            {{- end }}
          {{- end }}
          volumeMounts:
          {{- if or .Values.grpc.enabled .Values.grpcExt.enabled }}
          - name: grpc
            mountPath: /netigate/cert/
            readOnly: true
          {{- end }}
          {{- if .Values.kafka.enabled }}
          - name: kafka
            mountPath: /netigate/kafka/
            readOnly: true
          {{- end }}
          {{- if .Values.vault.env }}
          - name: secrets-mount
            mountPath: /mnt/secrets-store
            readOnly: true          
          {{- end }}
          {{- if or .Values.secret .Values.enabled  }}
          envFrom:
            {{- if .Values.secret }}
            - secretRef:
                name: {{ .Values.name }}
            {{- end }}
            {{- if and .Values.enabled .Values.vault.env  }}
            - secretRef:
                name: {{ .Values.name }}-secret
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: http-metrics
              containerPort: {{ .Values.metrics.containerPort }}
              protocol: TCP
            {{- end }}
            {{- if or .Values.grpc.enabled .Values.grpcExt.enabled }}
            - name: https
              containerPort: {{ .Values.grpc.containerPort }}
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 10 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if or .Values.grpc.enabled .Values.grpcExt.enabled }}
      - secret:
          secretName: grpc-wildcard-certificate
        name: grpc
      {{- end }}
      {{- if .Values.vault.env }}
      - name: secrets-mount
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.name }}-secret"
      {{- end }}
      {{- if .Values.kafka.enabled }}
      - secret:
          secretName: kafka-{{ .Values.kafka.cluster }}-{{ .Values.kafka.app }}
        name: kafka
      {{- end }}