{{- if .Values.vault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    {{- range .Values.vault.env }}
    - key: {{ .key }}
      objectName: {{ .key }}
    {{- end }}
    secretName: {{ .Values.name }}-secret
    type: Opaque
  parameters:
    vaultAddress: "https://vault.int.{{ .Values.environmentFQDN }}"
    roleName: {{ .Values.name }}
    objects: |
      {{- range .Values.vault.env }}
      - objectName: "{{ .key }}"
        secretPath: "{{ $.Values.vault.team }}/data/{{ $.Values.name }}/config"
        secretKey: "{{ .key }}"
      {{- end }}
{{ end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: generic-psql-connections-string
      objectName: generic-psql-connections-string
    - key: psql-connections-string
      objectName: psql-connections-string
    secretName: {{ .Values.name }}-postgres
    type: Opaque
  parameters:
    vaultAddress: "https://vault.int.{{ .Values.environmentFQDN }}"
    roleName: {{ .Values.name }}
    objects: |
      - objectName: "generic-psql-connections-string"
        secretPath: "data-credentials/postgres/{{ $.Values.postgres.databaseServer }}/data/{{ $.Values.postgres.databaseName }}"
        secretKey: "generic-psql-connections-string"
      - objectName: "psql-connections-string"
        secretPath: "data-credentials/postgres/{{ $.Values.postgres.databaseServer }}/data/{{ $.Values.postgres.databaseName }}"
        secretKey: "psql-connections-string"
{{ end }}
---
{{- if .Values.kafka.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-kafka
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: access-cert
      objectName: access-cert
    - key: access-key
      objectName: access-key
    - key: ca-cert
      objectName: ca-cert
    - key: schema-registry-uri
      objectName: schema-registry-uri
    - key: service-uri
      objectName: service-uri
    - key: username
      objectName: username
    secretName: {{ .Values.name }}-kafka
    type: Opaque
  parameters:
    vaultAddress: "https://vault.int.{{ .Values.environmentFQDN }}"
    roleName: {{ .Values.name }}
    objects: |
      - objectName: "access-cert"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "access-cert"
      - objectName: "access-key"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "access-key"
      - objectName: "ca-cert"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "ca-cert"
      - objectName: "schema-registry-uri"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "schema-registry-uri"
      - objectName: "service-uri"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "service-uri"
      - objectName: "username"
        secretPath: "data-credentials/kafka/{{ $.Values.kafka.cluster }}/data/{{ $.Values.kafka.app }}"
        secretKey: "username"
{{ end }}
---
{{- if .Values.redis.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: redis-service_uri
      objectName: redis-service_uri
    - key: redis-username
      objectName: redis-username
    - key: redis-password
      objectName: redis-password
    secretName: {{ .Values.name }}-redis
    type: Opaque
  parameters:
    vaultAddress: "https://vault.int.{{ .Values.environmentFQDN }}"
    roleName: {{ .Values.name }}
    objects: |
      - objectName: "redis-service_uri"
        secretPath: "data-credentials/redis/{{ $.Values.redis.databaseServer }}/data/{{ $.Values.redis.databaseName }}"
        secretKey: "redis-service_uri"
      - objectName: "redis-username"
        secretPath: "data-credentials/redis/{{ $.Values.redis.databaseServer }}/data/{{ $.Values.redis.databaseName }}"
        secretKey: "redis-username"
      - objectName: "redis-username"
        secretPath: "data-credentials/redis/{{ $.Values.redis.databaseServer }}/data/{{ $.Values.redis.databaseName }}"
        secretKey: "redis-username"
{{ end }}
---