{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    team: {{ .Values.team }}
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .name }}: {{ .data| b64enc | quote }}
  {{- end }}
{{- end }}