{{ range .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ range .ingress.annotations }}
    {{ . }}
    {{ end }}
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  ingressClassName: {{ $.Values.ingressClass}}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .ingress.paths.backendServicePort }}
            path: {{ .ingress.paths.path }}
            pathType: Prefix
  tls:
    - hosts:
        - {{ .ingress.host }}
      secretName: {{ .ingress.secretName }}
{{ end }}