{{ range .Values.services}}
{{ if .serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: {{ .name }}-health
  namespace: {{ .namespace }}
spec:
  endpoints:
    - interval: 30s
      metricRelabelings:
        - replacement: {{ if eq .ingress.paths.backendServicePort 443 }}https://{{ else }}http://{{ end }}{{ .service.externalName }}{{ .serviceMonitor.path }}
          sourceLabels:
            - instance
          targetLabel: instance
        - replacement: {{ .ingress.host }}
          sourceLabels:
            - target
          targetLabel: target
      params:
        module:
          - http_get_2xx
        target:
          - {{ if eq .ingress.paths.backendServicePort 443 }}https://{{ else }}http://{{ end }}{{ .service.externalName }}{{ .serviceMonitor.path }}
      path: {{ .serviceMonitor.path }}
      port: http
      scheme: http
      scrapeTimeout: 30s
  jobLabel: prometheus-blackbox
  namespaceSelector:
    matchNames:
      - {{ .namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
{{ end }}
{{ end }}