{{- if .Values.postgres.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: generic-psql-connections-string
      objectName: generic-psql-connections-string
    - key: psql-connections-string
      objectName: psql-connections-string
    secretName: {{ .Values.name }}-postgres
    type: Opaque
  parameters:
    vaultAddress: "https://vault.infra.{{ .Values.environmentFQDN }}"
    roleName: {{ .Values.name }}
    objects: |
      - objectName: "generic-psql-connections-string"
        secretPath: "aiven/postgres/{{ $.Values.postgres.databaseServer }}/data/{{ $.Values.postgres.databaseName }}"
        secretKey: "generic-psql-connections-string"
      - objectName: "psql-connections-string"
        secretPath: "aiven/postgres/{{ $.Values.postgres.databaseServer }}/data/{{ $.Values.postgres.databaseName }}"
        secretKey: "psql-connections-string"
{{ end }}